### PR TITLE
feat: Cookbook Onboard integration

### LINKED ISSUE #73: Feat: Cookbook Onboard (AI Assistant)
## Feature Request
The AI assistant and co-pilot is trained on all existing Chronicle resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Chronicle Protocol, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to Chronicle-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

## Preview
https://chronicle-docs.vercel.app/

image

### PR DESCRIPTION
**Pull request by ClockRide**
| Q                        | A
| ------------------------ | ---
| Service                  | (gofer, spectre, spire etc)
| Fixed Issues?            | Resolves #73
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR         | `[skip-ci]`
| Any Dependency Changes?  | Added `@cookbookdev/docsbot` package
| License                  | AGPL

### Description of pull request

The AI assistant and co-pilot is trained on all existing Chronicle resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Chronicle Protocol, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to Chronicle-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

### Preview
https://chronicle-docs.vercel.app/

image

### CODE REVIEW

**Comment by biancabuzea200** [comment]
Hi, @ClockRide. Thank you so much for the contribution to you and the Cookbook team!

**Review by WesleyCharlesBlake — CHANGES_REQUESTED** [review]
@ClockRide @biancabuzea200 the `COOKBOOK_API_KEY` is public, can we provide this at deploy time through vercel to keep this api key protected?

**Comment by ClockRide** [comment]
> @ClockRide @biancabuzea200 the `COOKBOOK_API_KEY` is public, can we provide this at deploy time through vercel to keep this api key protected?

It's up to you. Either option works for us since it will be exposed to the public in HTTP requests to our backend anyway. By its nature, it's more of a public key/project ID. Still, let me know if you'd like me to obtain that from the environment variable (i.e., from `process.env`). Happy to make changes necessary :)

**Comment by WesleyCharlesBlake** [comment]
> > @ClockRide @biancabuzea200 the `COOKBOOK_API_KEY` is public, can we provide this at deploy time through vercel to keep this api key protected?
> 
> It's up to you. Either option works for us since it will be exposed to the public in HTTP requests to our backend anyway. By its nature, it's more of a public key/project ID. Still, let me know if you'd like me to obtain that from the environment variable (i.e., from `process.env`). Happy to make changes necessary :)

all good here! As long as theres no risk in terms of the exposed api key causing any abuse , then we're good

**Review by WesleyCharlesBlake — APPROVED** [review]

**Pull request merged**
